[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18.18.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  CI = "true"