// app/layout.js

// There should be NO 'use client' directive here.
// The very first line should probably be an import statement or a comment.

import { Geist, Geist_Mono } from "next/font/google"; // Or whatever fonts you're using
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = { // This is allowed because this file is a Server Component by default
  title: "EngAliVFX",
  description: "Generated by create next app",
  icons: "/favicon.ico" // Or { icon: '/favicon.ico' } as recommended earlier
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}


