// // app/layout.js

// // There should be NO 'use client' directive here.
// // The very first line should probably be an import statement or a comment.

// import { Geist, Geist_Mono } from "next/font/google"; // Or whatever fonts you're using
// import { GeistSans as VercelGeistSans, GeistMono as VercelGeistMono } from '@vercel/geist/font'; // Correct import for Geist fonts
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = { // This is allowed because this file is a Server Component by default
//   title: "EngAliVFX",
//   description: "Generated by create next app",
//   icons: "/favicon.ico" // Or { icon: '/favicon.ico' } as recommended earlier
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// app/layout.js

import './globals.css';
import { GeistSans as VercelGeistSans, GeistMono as VercelGeistMono } from '@vercel/geist/font'; // Correct import for Geist fonts


const geistSans = VercelGeistSans; // No need for .variable here if directly using the font object
const geistMono = VercelGeistMono;


export const metadata = {
  title: "EngAliVFX",
  description: "Generated by create next app",
  icons: "/favicon.ico"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // Use the class names provided by @vercel/geist/font
        className={`${geistSans.className} ${geistMono.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}